# Generated by Django 5.2.4 on 2025-07-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
